server:
  port: 8000
spring:
  data:
    mongodb:
      authentication-database: autoEventWisher
      auto-index-creation: true
      host: mongo
      port: 27017
      username: aaron
      password: favre
      database: autoEventWisher
mongodb.encrypt:
  keys:
    - version: 1
      key: hqHKBLV83LpCqzKpf8OvutbCs+O5wX5BPu3btWpEvXA=

messaging:
  twilio:
    accountSid: #Enter your configured sid from twilio
    authToken: #Enter your authtoken from twilio
    senderPhoneNumber: #Enter the phone number that you setup in twilio

graphql:
  servlet.mapping: /apis/graphql
  playground:
    enabled: true
    endpoint: /apis/graphql
    staticPath.base: /vendor/playground
    tabs:
      - name: Find Event Config By Id
        query: classpath:playground/findEventById.graphql
        variables: classpath:playground/findEventById_variables.json
      - name: Create Event Config
        query: classpath:playground/createSingleEvent.graphql
        variables: classpath:playground/createSingleEvent_variables.json